### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by zecolher** [exult/ExultAndroid#2]
Okay, I built the source without changing anything, but when I start the app it instantly crashes, giving me a null pointer exception

**Comment by DominusExult** [comment]
This port to Android is very old by now and never even close to being finished. Probably a lot of things changed since then. You are more likely to succeed by adapting the native Android patch  
http://goo.gl/E2y7Z. Since that patch we changed a lot of stuff, most importantly we switched to SDL2 which is much more compatible with Android. Also the port to iOS is probably helpful as some kind of guidance what needs to be done to make it work 
https://github.com/litchie/exult-ios

**Comment by marzojr** [comment]
This port isn't really being maintained or developed anymore; I forgot to archive it when I split the SVN repository into three. I will do it now.
